<?php

namespace GM\ProjetBundle\Repository;

/**
 * CollaborateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollaborateurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getColl(){
        $rsm = new \Doctrine\ORM\Query\ResultSetMapping();
      $query = $this->getEntityManager()->createNativeQuery(
              'select id, user FROM collaborateur ', $rsm);
      
      return $query->getr;
    }
    
    public function getAllWithoutProject()
    {

            $q1=$this->getEntityManager()->getRepository('GMProjetBundle:Projet')->createQueryBuilder('p')
                    ->select('c2.id')
                    ->join('p.collaborateurs','c2');

            $queryBuilder=$this->createQueryBuilder('c');
            
            $queryBuilder->where( $queryBuilder->expr()->notIn('c.id',$q1->getDQL()));
            
            return $queryBuilder->getQuery()->getResult();

    }
    
      public function getAllWithinProject()
    {

            $q1=$this->getEntityManager()->getRepository('GMProjetBundle:Projet')->createQueryBuilder('p')
                    ->select('c2.id')
                    ->join('p.collaborateurs','c2');

            $queryBuilder=$this->createQueryBuilder('c');
            
            $queryBuilder->where( $queryBuilder->expr()->In('c.id',$q1->getDQL()));
            
            return $queryBuilder->getQuery()->getResult();

    }
    
}
