services:
#    gm_projet.example:
#        class: GM\ProjetBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    gm_requete:
        class: GM\ProjetBundle\Service\Requete
        arguments: ["@database_connection"]

